# Generated by Django 6.0.4 on 2026-05-04 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_prenda_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='catalogo.prenda')),
            ],
            options={
                'verbose_name': 'Calificación de Prenda',
                'unique_together': {('prenda', 'comprador')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_vendedor_dadas', to=settings.AUTH_USER_MODEL)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_vendedor', to='catalogo.prenda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de Vendedor',
                'unique_together': {('vendedor', 'comprador', 'prenda')},
            },
        ),
    ]
